# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: yarn.lock
      - id: end-of-file-fixer
        exclude: yarn.lock
      - id: check-yaml
      - id: check-added-large-files
      - id: requirements-txt-fixer
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.(json|yaml|md|toml)$
        additional_dependencies:
          - "prettier-plugin-toml"
  - repo: https://github.com/shuklaayush/pre-commit-forge
    rev: v0.0.1
    hooks:
      - id: check-forge-snapshot
