[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  "forge-std/=lib/forge-std/src/",
  "multicall/=lib/multicall/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
]
verbosity = 3

[ci]
fuzz-runs = 10_000
