name: lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - run: |
          corepack enable

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Run prettier
        run: yarn prettier:check

  slither:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Slither
        uses: crytic/slither-action@main
        continue-on-error: true
        id: slither
        with:
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
