name: lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  slither:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Slither
        uses: crytic/slither-action@main
        continue-on-error: true
        id: slither
        with:
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
